### ISSUE TITLE
Idea regarding iptables rules validation

### ISSUE THREAD

**Issue by gmiu** [HubbleStack/Nova#120]
An idea just crossed my mind regarding this: what if we don't put the actual rule in the YAML.
We could support a dictionary, in the YAML, for the rule to be checked and, in that dictionary, to put the pieces needed to build that rule. 
Then, we could use [`iptables.build_rule`](https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.iptables.html#salt.modules.iptables.build_rule) to create that rule and, after that, checking its existence using `iptables.check`.

The YAML would look something like this:

```
firewall:
  whitelist:
     ssh:
       data:
         tag: 'FIREWALL-TCP-22'
         rule:
           table: 'filter'
           chain: 'INPUT'
           family: 'ipv4'
           state: 'ESTABLISHED,RELATED'
           jump: 'ACCEPT'
           dport: 22
           protocol: 'tcp'
       description: 'ssh iptables rule check'
```

**Comment by gmiu** [comment]
I can't assign more than one, so this is for @basepi also

**Comment by gmiu** [comment]
Or we could wait for this to be fixed: https://github.com/saltstack/salt/issues/33059

**Comment by basepi** [comment]
I think that's a great idea. Including the rule is nice because we can be precise, but it also allows for typos. If we construct the rules ourselves it might be less error-prone.

**Comment by gmiu** [comment]
@cedwards, what are your thoughts on this?

**Comment by cedwards** [comment]
+1

**Comment by gmiu** [comment]
Then I will work towards this.

**Comment by dgmorrisjr** [comment]
RE blacklisting - i suppose it's nice to be able to enumerate a list of rules we don't want.   but really this has some shortfalls.  
1. Typo's are already listed above
2. Variations - how many variations of a FTP rule could exist and how many do you want to be able to enumerate in this blacklist?
3. How do you alert on rules that are present that you did not intend to have on the system?  How do you alert for rules that are present that you did not previously enumerate in the blacklist?

Therefore, i'm wondering if you really just want to list the rules you expect to see (whitelist), then alert on any other rules that were found as they are potentially security issues

**Comment by basepi** [comment]
A true whitelist might be the way to go on this one, where anything not on the whitelist should be blacklisted.

**Comment by gmiu** [comment]
I propose this YAML format:

```
firewall:
  whitelist:

    ssh:
      data:
        tag: 'FIREWALL-TCP-22'
        table: 'filter'
        chain: INPUT
        family: 'ipv4'
        rule:
          proto: tcp
          dport: 22
          match: state
          connstate: RELATED,ESTABLISHED
          jump: ACCEPT
        description: 'ssh iptables rule check'
```

**Comment by dgmorrisjr** [comment]
Looks good, and would it follow the same structure as the salt states for defining firewall rules? For instance, here an example that uses a number of firewall options:

```
init_fw_salt_inbound:
  iptables.append:
    - name: salt_inboud
    - table: filter
    - chain: INPUT
    - proto: tcp
    - match:
      - multiport
      - state
      - policy
      - comment
    - ports: 4505:4506
    - connstate: NEW,ESTABLISHED,RELATED
    - dir: in
    - pol: ipsec
    - comment: Allow Salt
    - jump: ACCEPT
```
