### ISSUE TITLE
Control cve_scan based on score 

### ISSUE THREAD

**Issue by jaredhanson11** [HubbleStack/Nova#162]
We were hoping to add additional functionality that allows the cve_scan to only report vulnerabilities under a certain score. Maybe something like

```
control:
  cve_scan_v2: 4.0 
```

in the top level of the yaml, that tells hubble to filter low enough scores from the `Failed` to `Controlled` sections of the cve_scan_v2 module.

**Comment by basepi** [comment]
This seems reasonable, as we discussed in person. Feel free to submit the code you showed me as a pull request.

**Comment by jaredhanson11** [comment]
#170 allows you to control based on score by adding `'control'` in the yaml profile as follows.

```
cve_scan_v2:
    url: http://vulners.com/
    ttl: 86400
    control:
        score: 4
```
