### ISSUE TITLE
Report "compliance level" in audit output

### ISSUE THREAD

**Issue by cedwards** [HubbleStack/Nova#20]
It would be a nice feature to return a "compilance level" value in the audit output. ie;

```
local:
    ----------
    Failure:
        - CIS-6.1.11
        - CIS-1.5.1
        - CIS-1.5.2
    Success:
        - CIS-6.2.3
        - CIS-4.5.3
        - CIS-9.1.7
        - CIS-9.1.8
        - CIS-6.1.10
        - CIS-9.1.6
        - CIS-4.5.5
        - CIS-8.1
        - CIS-9.1.9
        - CIS-9.1.3
        - CIS-9.1.2
        - CIS-9.1.5
        - CIS-9.1.4
        - CIS-6.1.8
        - CIS-6.1.9
        - CIS-6.1.6
        - CIS-6.1.7
        - CIS-6.1.4
        - CIS-6.1.5
        - CIS-6.1.3

    Compliance Level: XX%
```
