### ISSUE TITLE
Matches on pam configuration files failing

### ISSUE THREAD

**Issue by rterbush** [HubbleStack/Nova#257]
Completely stumped as to why this is failing. Possibly related to the report in #61 

Currently focused on <code>CIS-5.3.4: Ensure password hashing algorithm is SHA-512</code>

grep at the command line matches on the file

```
$ grep -E '^password\s+\w+\s+pam_unix\.so.*sha512.*' /etc/pam.d/password-auth
password    sufficient    pam_unix.so sha512 shadow nullok try_first_pass use_authtok
```

The above should be enough to satisfy the CIS rule. As described below

``` yaml
    password_hash:
      data:
        CentOS Linux-7:
        - /etc/pam.d/password-auth:
            pattern: '^password\s+\w+\s+pam_unix\.so.*sha512.*'
            grep_args:
              - '-E'
            tag: CIS-5.3.4
      description: Ensure password hashing algorithm is SHA-512
```

Note: this current pattern deviates from the current file in develop branch which does not match at all.

osfinger returns

```
myminion:
    CentOS Linux-7
```

Which is applying <code>cis/centos-7-level-1-scored-v2-1-0.yaml</code>

Any help to track this down would be appreciated.  I am stumped.
