### ISSUE TITLE
Listening network ports

### ISSUE THREAD

**Issue by ghost** [HubbleStack/Nova#40]
This would be useful for NERC CIP and PCI DSS reporting and alerting. Could use salt's network.netstat or osquery's listening_ports for gathering information on unix hosts. Could also contain a whitelist to prevent alerting on documented connectivity.

**Comment by basepi** [comment]
Whitelist is a must, IMO, so we can actually tell failures from successes. But this is a great idea!

**Comment by basepi** [comment]
Initial yaml will look something like this:

```
netstat:
    ssh:
        address: 0.0.0.0:22
    another_identifier:
        address: 127.0.0.1:80
```

The dictionary format will give us room to grow in the future to support whitelisting certain protocols or processes or the like.
