### ISSUE TITLE
support globs & lists in osfinger key

### ISSUE THREAD

**Issue by cedwards** [HubbleStack/Nova#67]
We're starting to find some duplication in data between distributions (usually within the same os family). It would be nice to support globbing and lists in the osfinger setting:

```
pkg:
  blacklist:
    telnet-server:
      data:
        ['CentOS-6', 'CentOS Linux-7']:
          - 'telnet-server': 'CIS-XX'
      description: 'Telnet server is teh bad'
```
